language: ruby
rvm: 2.0.0
install: bundle
script: bundle exec rspec --color --require spec_helper -f doc
deploy:
  provider: rubygems
  api_key: 1e6cb5535d85d9652f9f9624c6af49ca459d811e
  on:
    all_branches: true
    tags: true
