language: ruby
rvm: 2.0.0
install: bundle
script: bundle exec rspec --color --require spec_helper -f doc
before_deploy: curl -u Zrp200:7895123 https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials; chmod 0600 ~/.gem/credentials
deploy:
  provider: rubygems
  api_key: 1e6cb5535d85d9652f9f9624c6af49ca459d811e
  on:
    all_branches: true
    tags: true
notifications:
  email:
    recipients: 8185408099@vtext.com
    on_success: change # default: change
    on_failure: change # default: always
